# Uncomment the next line to define a global platform for your project
 platform :ios, '15.1'

target 'BPCinema' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 7.6.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # Pods for BPCinema

end
